### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by maximesunnen** [maximesunnen/flowFate#3]
- [x] add two subsequent curating steps
- [x] add modals for non-unique channel/control names
- [x] add "Reset" button when users still add the incorrect gate
- [x] create_quantile_gate( ) function should use a channel argument: right now it is "GRN.B.HLin" but since this might be different for different users and to reuse the function for a different channel this should depend on the input of the user (same for output$overview_SSC_FSC in import module)
- [x] module curate: can be simplified. I fetch nonDebris_data twice (for different indices). I could fetch it once and index later differently
- [ ] with autoWaiter() when the app opens, there is a very brief "flash" of the loading screen, which should not at all be there
- [x] user curates once, then changes an input: should get a message saying "Restart curation". If not the app crashes.
- [x] observer, after "restart curation" should not schedule to recompute right away (maybe with a req() statement)
- [x] #16
- [x] reshape Curate module: there are many simplifications that can be done
- [x] discuss how data should be visualized in "Gate" module. This is especially crucial when users analyze many samples (e.g. 40+, which is quite common, especially when they have appropriate software, then they're motivated to analyze more samples simultaneously)
- [x] agree on an export format (plots, flat file)
- [x] "Gate now" button conditionally visible (not sure when exactly, tbd)
- [x] module "Curate", line 136: add comments to how this code works!!!
- [x] #17
- [ ] document all my custom functions!
- [x] "Gate now" button currently only works if there are really 2 GFP bins. I think when we're reaching the end of development, we should change this behavior as this gives more flexibility to the user.
- [x] in gate module: after bins created and button "Gate now" clicked, have some sort of "display" of the current state (maybe the plot(r$gs)?) or detailed description in the text ("Your bins have been created")
- [x] #18
- [x] reshape all modules to to work with reactive expressions instead of observers
- [x] content = function(file) {write.csv(output_test, file)}) I don't understand this syntax
- [x] our getData_splitPeak function does not have a filterId yet!!! must change this
- [ ] #19
- [ ]  gate module: ideally we make it that the controller only has the options that are possible, e.g. if user adds  GFP-low bin he can't select GFP-medium on the controller
- [x] when user decides to reset bins, all bins should be removed: right now they're removed from the gatingSet, but not visually. if the user adds 2 bins, then resets, he will still SEE 2 bins and can't e.g. only use the first one
- [x] import module (or maybe all modules): updateTabsetPanel( )
- [x] DT table: can we make the first row of the table selected. to indicate to the user that you can click on the rows
- [x] res = 120 in all plots, all modules
- [x] #20
- [x] pkgdown
- [x] demo fcs file (see issue)
- [x] final modification in the curate module would be to make sure that after the reset button is clicked, the plots in the NonDebris and GFP gate tab disappear (this is currently not implemented as the plots are tied to a bindEvent(input$Curate) call so they don't update once the user resets this. a reactive val may help here.
